owner: andreesg # Your GitHub username
repo: intk-upptime # Your Github repository name

sites:
  - name: Centraal Museum
    url: https://www.centraalmusuem.nl

status-website:
  baseUrl: /intk-upptime
  logoUrl: https://old.intk.com/logo.png
  name: INTK
  introTitle: "Monitor the uptime of INTK projects"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO